"""The RFC 9162 (Certificate Transparency v2) Merkle tree.

The receipt log, and each receipt's row commitment, is this tree, exactly as
RFC 9162 section 2.1 defines it, rather than a structure of our own. That is
the point: every CT monitor, auditor and proof library already implements it,
and anyone can check an ARC1 proof with one of them.

- ``MTH({}) = SHA-256()``
- ``MTH({d0}) = SHA-256(0x00 || d0)``
- ``MTH(D[n]) = SHA-256(0x01 || MTH(D[0:k]) || MTH(D[k:n]))``, where ``k`` is
  the largest power of two smaller than ``n``.

The ``0x00``/``0x01`` prefixes keep a leaf from ever hashing like an inner
node, so a forged proof cannot pass a node off as a leaf or the reverse.

Inclusion and consistency proofs are generated by the RFC's ``PATH`` and
``PROOF`` recursions and verified by the iterative algorithms of sections
2.1.3.2 and 2.1.4.2, transcribed step for step.
"""

from __future__ import annotations

import hashlib
import hmac
from collections.abc import Iterable, Sequence

__all__ = [
    "EMPTY_ROOT",
    "MerkleTree",
    "leaf_hash",
    "node_hash",
    "verify_consistency",
    "verify_inclusion",
]

EMPTY_ROOT = hashlib.sha256(b"").digest()
"""The root of the empty tree, ``SHA-256()``."""


def leaf_hash(data: bytes) -> bytes:
    """``SHA-256(0x00 || data)``: the hash of one leaf."""
    return hashlib.sha256(b"\x00" + data).digest()


def node_hash(left: bytes, right: bytes) -> bytes:
    """``SHA-256(0x01 || left || right)``: the hash of an inner node."""
    return hashlib.sha256(b"\x01" + left + right).digest()


def _split(n: int) -> int:
    """The largest power of two strictly smaller than ``n`` (``n >= 2``)."""
    return 1 << ((n - 1).bit_length() - 1)


class MerkleTree:
    """An append-only RFC 9162 tree over leaf hashes.

    The hash of every complete, aligned subtree (a power-of-two run of leaves
    starting at a multiple of its size) is computed once and cached: such a
    subtree never changes as the tree grows. A root or a proof for any size
    then costs O(log n) hashes once the cache is warm.

    :param leaf_hashes: Initial leaves, already hashed with :func:`leaf_hash`.
    """

    __slots__ = ("_cache", "_leaves")

    def __init__(self, leaf_hashes: Iterable[bytes] = ()) -> None:
        self._leaves: list[bytes] = []
        self._cache: dict[tuple[int, int], bytes] = {}
        for leaf in leaf_hashes:
            self.append(leaf)

    def __len__(self) -> int:
        return len(self._leaves)

    def append(self, leaf: bytes) -> int:
        """Add one leaf hash and return its index.

        :raises ValueError: If ``leaf`` is not a 32-byte hash.
        """
        if len(leaf) != 32:
            raise ValueError(f"a leaf hash is 32 bytes, got {len(leaf)}")
        self._leaves.append(leaf)
        return len(self._leaves) - 1

    def leaf(self, index: int) -> bytes:
        """The hash of leaf ``index``."""
        return self._leaves[index]

    def root(self, size: int | None = None) -> bytes:
        """``MTH`` of the first ``size`` leaves (all of them by default)."""
        n = self._size(size)
        return self._hash(0, n) if n else EMPTY_ROOT

    def inclusion_proof(self, index: int, size: int | None = None) -> list[bytes]:
        """RFC 9162 ``PATH(index, D[size])``: the audit path for one leaf.

        :raises ValueError: If ``index`` is not a leaf of a tree of ``size``.
        """
        n = self._size(size)
        if not 0 <= index < n:
            raise ValueError(f"leaf {index} is not in a tree of size {n}")
        return self._path(index, 0, n)

    def consistency_proof(self, old_size: int, new_size: int | None = None) -> list[bytes]:
        """RFC 9162 ``PROOF(old_size, D[new_size])``.

        Empty when either size is zero or the sizes are equal: the empty tree
        is a prefix of every tree, and every tree of its own.

        :raises ValueError: If ``old_size`` exceeds ``new_size``.
        """
        n = self._size(new_size)
        if not 0 <= old_size <= n:
            raise ValueError(f"cannot prove a tree of size {old_size} is a prefix of size {n}")
        if old_size in (0, n):
            return []
        return self._subproof(old_size, 0, n, complete=True)

    # -- the RFC recursions ---------------------------------------------

    def _size(self, size: int | None) -> int:
        if size is None:
            return len(self._leaves)
        if not 0 <= size <= len(self._leaves):
            raise ValueError(f"the tree has {len(self._leaves)} leaves, not {size}")
        return size

    def _hash(self, start: int, n: int) -> bytes:
        if n == 1:
            return self._leaves[start]
        aligned = n & (n - 1) == 0
        if aligned:
            cached = self._cache.get((start, n))
            if cached is not None:
                return cached
        k = _split(n)
        result = node_hash(self._hash(start, k), self._hash(start + k, n - k))
        if aligned:
            self._cache[(start, n)] = result
        return result

    def _path(self, index: int, start: int, n: int) -> list[bytes]:
        if n == 1:
            return []
        k = _split(n)
        if index < k:
            return [*self._path(index, start, k), self._hash(start + k, n - k)]
        return [*self._path(index - k, start + k, n - k), self._hash(start, k)]

    def _subproof(self, m: int, start: int, n: int, *, complete: bool) -> list[bytes]:
        if m == n:
            return [] if complete else [self._hash(start, n)]
        k = _split(n)
        if m <= k:
            return [*self._subproof(m, start, k, complete=complete), self._hash(start + k, n - k)]
        return [*self._subproof(m - k, start + k, n - k, complete=False), self._hash(start, k)]


def verify_inclusion(
    leaf: bytes, index: int, size: int, proof: Sequence[bytes], root: bytes
) -> bool:
    """RFC 9162 section 2.1.3.2: is ``leaf`` at ``index`` in the tree ``root``?"""
    if not 0 <= index < size:
        return False
    fn, sn = index, size - 1
    r = leaf
    for p in proof:
        if sn == 0:
            return False
        if fn & 1 or fn == sn:
            r = node_hash(p, r)
            if not fn & 1:
                while fn and not fn & 1:
                    fn >>= 1
                    sn >>= 1
        else:
            r = node_hash(r, p)
        fn >>= 1
        sn >>= 1
    return sn == 0 and hmac.compare_digest(r, root)


def verify_consistency(
    old_size: int,
    new_size: int,
    old_root: bytes,
    new_root: bytes,
    proof: Sequence[bytes],
) -> bool:
    """RFC 9162 section 2.1.4.2: is the tree ``old_root`` a prefix of ``new_root``?

    Two cases the RFC leaves to the caller are settled here: equal sizes need
    an empty proof and equal roots, and the empty tree needs an empty proof
    and the empty root.
    """
    if not 0 <= old_size <= new_size:
        return False
    if old_size == new_size:
        return not proof and hmac.compare_digest(old_root, new_root)
    if old_size == 0:
        return not proof and hmac.compare_digest(old_root, EMPTY_ROOT)
    if not proof:
        return False
    path = list(proof)
    if old_size & (old_size - 1) == 0:
        path.insert(0, old_root)
    fn, sn = old_size - 1, new_size - 1
    while fn & 1:
        fn >>= 1
        sn >>= 1
    fr = sr = path[0]
    for c in path[1:]:
        if sn == 0:
            return False
        if fn & 1 or fn == sn:
            fr = node_hash(c, fr)
            sr = node_hash(c, sr)
            if not fn & 1:
                while fn and not fn & 1:
                    fn >>= 1
                    sn >>= 1
        else:
            sr = node_hash(sr, c)
        fn >>= 1
        sn >>= 1
    return sn == 0 and hmac.compare_digest(fr, old_root) and hmac.compare_digest(sr, new_root)
