"""Generate the ARC1 reference test vectors in ``vectors/arc1/``.

Everything here is deterministic: the keys come from fixed, published seeds
(test-only, never use them for anything real), every clock and identifier is
fixed, and Ed25519 signatures are deterministic. Running this twice writes
identical bytes, and ``tests/test_receipt_vectors.py`` regenerates the
vectors on every CI run and fails if a committed file differs from what the
code produces today.

Needs the ``cryptography`` package to sign (``uv sync`` installs it for
development). Verifying the vectors needs nothing but the standard library.

Usage::

    uv run python scripts/generate_arc1_vectors.py [--out vectors/arc1]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tempfile
import uuid
from collections.abc import Sequence
from dataclasses import replace
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any

from agentgov.receipts import (
    ActionReceipt,
    Anchors,
    Authority,
    Capability,
    ChainAnchor,
    CheckerRecord,
    Checkpoint,
    CheckpointPolicy,
    Cost,
    Coverage,
    Decision,
    Ed25519Signer,
    Effect,
    FileWitness,
    HmacKey,
    InclusionProof,
    Intent,
    MerkleTree,
    Outcome,
    OutcomeStatus,
    ReceiptBundle,
    ReceiptLog,
    RowChange,
    RowCommitment,
    StatedFootprint,
    canonical_bytes,
    commit_rows,
)
from agentgov.receipts.merkle import leaf_hash
from agentgov.receipts.schema import Signature

LOG_ID = "arc1-vectors"
WITNESS_ID = "arc1-vectors-witness"
_NAMESPACE = uuid.UUID("5f3c9b1e-0a4d-4e6b-9c2f-7d1e8a0b3c4d")
_BASE = datetime(2026, 9, 25, 14, 0, 0, tzinfo=UTC)


_README = """\
# ARC1 reference test vectors

Generated by [`scripts/generate_arc1_vectors.py`](../../scripts/generate_arc1_vectors.py).
Do not edit by hand. The test suite regenerates this directory on every run
and fails if a single byte differs
([`tests/test_receipt_vectors.py`](../../tests/test_receipt_vectors.py)). The
format is specified in [`docs/RECEIPTS.md`](../../docs/RECEIPTS.md).

> **The keys in `keys/` are test keys.** `issuer.seed` and `witness.seed`
> are Ed25519 private seeds, and `internal.hmac` is an HMAC secret. All three
> are published, and derived from public labels, so that anyone can reproduce
> these files. Never use them for anything else.

## Layout

- `canonical.json`: RFC 8785 cases. Inputs, their exact canonical UTF-8, and
  texts a strict decoder must refuse.
- `merkle.json`: the RFC 9162 eight-leaf reference tree. Every root, and
  every inclusion and consistency proof.
- `ed25519.json`: the RFC 8032 section 7.1 signatures, a wrong message, and
  an `S` at or above the group order.
- `keys/`: `issuer.pub` and `witness.pub`, the keys a verifier trusts;
  `internal.hmac`; and the test seeds.
- `log/receipts.jsonl`: a durable receipt log of seven receipts. Each line is
  one canonical receipt, and exactly one Merkle leaf.
- `log/receipts.jsonl.checkpoints`: the log's signed checkpoints at sizes 3,
  5 and 7.
- `log/consistency.json`: the consistency proof from size 3 to 7 that the
  witness checked before it cosigned size 7.
- `witness/cosignatures.jsonl`: the witness's cosignatures of sizes 3 and 7.
  Size 5 was never shown to it.
- `valid/`: bundles and row disclosures that verify.
- `invalid/`: each one broken in exactly one way.
- `manifest.json`: every command-line case, and the exit code it must produce.

## The receipts

A support agent works a tenant-partitioned orders database, under a
capability for one tenant:

0. `committed-refund`: refunds one order, 3 rows. Committed.
1. An address update. Committed.
2. A support note. Committed.
3. `refused-tenant-wipe`: a prompt-injected plan that zeroes every tenant's
   totals and deletes the audit trail, 229 rows. Refused, and rolled back.
4. `scoped-repair`: the one-row fix the refused plan should have been. Its
   `decision.repair_of` names receipt 3. Committed.
5. `recovered-commit`: resolved after a crash, from the escrow chain's commit
   marker. `recovered_committed`.
6. `halted-scope`: admitted by every check, and refused because the scope was
   halted.

## Running the cases

From this directory:

```console
$ agentgov verify-receipt valid/committed-refund.bundle.json --pubkey keys/issuer.pub \\
      --witness witness/cosignatures.jsonl --witness-pubkey keys/witness.pub \\
      --rows valid/committed-refund.rows.json
```

Each case in `manifest.json` gives the arguments, as paths relative to this
directory, and the exit code: 0 pass, 3 malformed, 4 receipt signature, 5 log
inclusion, 6 witness, 8 rows. A conforming verifier produces the same code
for every case.
"""


def seed(label: str) -> bytes:
    """A published test-only key seed. NEVER use these outside tests."""
    return hashlib.sha256(
        f"ARC1 test vector {label} key; never use outside tests".encode()
    ).digest()


def _uuid(label: str) -> str:
    return str(uuid.uuid5(_NAMESPACE, label))


def _digest(label: str) -> str:
    return hashlib.sha256(label.encode()).hexdigest()


class _Clock:
    """A clock that ticks a fixed step on every call, for deterministic output."""

    def __init__(self, start: datetime, step: timedelta) -> None:
        self._now, self._step = start, step

    def __call__(self) -> datetime:
        now, self._now = self._now, self._now + self._step
        return now


def _write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------
# Realistic plans: what a support agent actually did to a production database
# --------------------------------------------------------------------------

_TENANTS = ("acme", "globex", "initech", "umbrella")
_CHECKERS = ("blast_radius", "tenant_isolation", "no_delete", "stated_footprint")


def _checkers(*names: str) -> tuple[CheckerRecord, ...]:
    return tuple(CheckerRecord(name, _digest(f"checker-config:{name}:v3")) for name in names)


def _refund_rows() -> list[RowChange]:
    return [
        RowChange.from_values(
            "orders",
            1042,
            tenant="acme",
            before={
                "id": 1042,
                "tenant": "acme",
                "customer": 77,
                "total": "480.00",
                "status": "paid",
            },
            after={
                "id": 1042,
                "tenant": "acme",
                "customer": 77,
                "total": "480.00",
                "status": "refunded",
            },
        ),
        RowChange.from_values(
            "refunds",
            3310,
            tenant="acme",
            before=None,
            after={
                "id": 3310,
                "tenant": "acme",
                "order_id": 1042,
                "amount": "480.00",
                "reason": "damaged in transit",
            },
        ),
        RowChange.from_values(
            "order_audit",
            88211,
            tenant="acme",
            before=None,
            after={"id": 88211, "order_id": 1042, "note": "refund 3310 issued by support-agent"},
        ),
    ]


def _wipe_rows() -> list[RowChange]:
    """The prompt-injection plan interlock's demo refuses: 63 order totals
    zeroed, 63 audit notes written, 103 audit rows deleted, across 4 tenants."""
    rows: list[RowChange] = []
    for i in range(63):
        tenant = _TENANTS[i % 4]
        total = f"{(i * 37) % 900 + 12}.{i % 100:02d}"
        rows.append(
            RowChange.from_values(
                "orders",
                2000 + i,
                tenant=tenant,
                before={"id": 2000 + i, "tenant": tenant, "total": total, "status": "paid"},
                after={"id": 2000 + i, "tenant": tenant, "total": "0.00", "status": "paid"},
            )
        )
    for i in range(63):
        tenant = _TENANTS[i % 4]
        rows.append(
            RowChange.from_values(
                "order_audit",
                90000 + i,
                tenant=tenant,
                before=None,
                after={"id": 90000 + i, "order_id": 2000 + i, "note": "total corrected"},
            )
        )
    for i in range(103):
        tenant = _TENANTS[i % 4]
        rows.append(
            RowChange.from_values(
                "order_audit",
                70000 + i,
                tenant=tenant,
                before={"id": 70000 + i, "order_id": 1500 + i, "note": "payment captured"},
                after=None,
            )
        )
    return rows


def _single_row(
    table: str, pk: int, tenant: str, column: str, old: str, new: str
) -> list[RowChange]:
    return [
        RowChange.from_values(
            table,
            pk,
            tenant=tenant,
            before={"id": pk, "tenant": tenant, column: old},
            after={"id": pk, "tenant": tenant, column: new},
        )
    ]


def _receipt(
    name: str,
    minute: int,
    commitment: RowCommitment,
    *,
    scope: str,
    tenants: Sequence[str],
    admitted: bool,
    status: OutcomeStatus,
    cost: str,
    calls: int,
    stated_rows: int,
    checkers: Sequence[str] = _CHECKERS,
    repair_of: str | None = None,
    escrow_seq: int | None = None,
) -> ActionReceipt:
    tables = sorted({row.table for row in commitment.rows})
    return ActionReceipt(
        receipt_id=_uuid(f"receipt:{name}"),
        issued_at=_BASE + timedelta(minutes=minute, microseconds=minute * 1111),
        issuer="interlock/0.2.0 support-eu-1",
        authority=Authority(
            scope_path=("orchestrator", scope),
            trajectory_id=f"traj-{_digest(name)[:12]}",
            capability=Capability(
                grant=f"grant:{scope}/tables-rw@v3",
                tables=("order_audit", "orders", "refunds", "customers", "support_notes"),
                tenants=tuple(tenants),
                row_limit=8,
            ),
        ),
        intent=Intent(
            plan_hash=_digest(f"plan:{name}"),
            stated=StatedFootprint(rows=stated_rows, tables=tuple(tables)),
        ),
        effect=Effect(
            substrate_id="sqlite",
            schema_hash=_digest("schema:support.db@migration-0042"),
            diff_hash=_digest(f"diff:{name}"),
            row_root=commitment.root,
            row_count=commitment.count,
            summary=commitment.summary(),
            truncated=False,
        ),
        coverage=Coverage(
            observed_tables=("customers", "order_audit", "orders", "refunds", "support_notes"),
            cascade_closed=True,
            authorizer_on=True,
            known_gaps=("rows written by database triggers into unobserved tables",),
        ),
        decision=Decision(
            verdict_hash=_digest(f"verdict:{name}"),
            admitted=admitted,
            checkers=_checkers(*checkers),
            policy_epoch=7,
            repair_of=repair_of,
        ),
        cost=Cost(
            ledger_txn_ids=tuple(_uuid(f"txn:{name}:{i}") for i in range(calls)),
            settled_usd=Decimal(cost),
            served_models=("claude-sonnet-5",),
        ),
        outcome=Outcome(
            status=status,
            substrate_txid=f"stage:{_uuid(f'stage:{name}')}",
        ),
        anchors=Anchors(
            agentgov=ChainAnchor(seq=1000 + minute * 7, head=_digest(f"agentgov-head:{name}")),
            escrow=ChainAnchor(seq=escrow_seq, head=_digest(f"escrow-head:{name}"))
            if escrow_seq is not None
            else None,
        ),
    )


def _scenarios() -> list[tuple[str, ActionReceipt, RowCommitment]]:
    def commit(name: str, rows: list[RowChange]) -> RowCommitment:
        return commit_rows(rows, secret=seed(f"row-secret:{name}"))

    refund = commit("committed-refund", _refund_rows())
    address = commit(
        "committed-address-update",
        _single_row("customers", 5521, "globex", "address", "12 Elm St", "12 Elm Street, Apt 4"),
    )
    note = commit(
        "committed-note",
        [
            RowChange.from_values(
                "support_notes",
                661,
                tenant="initech",
                before=None,
                after={
                    "id": 661,
                    "tenant": "initech",
                    "body": "Customer asked for an invoice copy",
                },
            )
        ],
    )
    wipe = commit("refused-tenant-wipe", _wipe_rows())
    repair = commit(
        "scoped-repair",
        _single_row("orders", 2004, "acme", "total", "160.04", "148.04"),
    )
    recovered = commit(
        "recovered-commit",
        _single_row("orders", 1077, "acme", "status", "paid", "shipped"),
    )
    halted = commit(
        "halted-scope",
        _single_row("orders", 1099, "umbrella", "status", "paid", "cancelled"),
    )
    wipe_receipt = _receipt(
        "refused-tenant-wipe",
        30,
        wipe,
        scope="support-agent",
        tenants=_TENANTS,
        admitted=False,
        status=OutcomeStatus.REFUSED,
        cost="0.00613500",
        calls=1,
        stated_rows=6,
    )
    return [
        (
            "committed-refund",
            _receipt(
                "committed-refund",
                0,
                refund,
                scope="support-agent",
                tenants=("acme",),
                admitted=True,
                status=OutcomeStatus.COMMITTED,
                cost="0.00549500",
                calls=2,
                stated_rows=3,
            ),
            refund,
        ),
        (
            "committed-address-update",
            _receipt(
                "committed-address-update",
                9,
                address,
                scope="support-agent",
                tenants=("globex",),
                admitted=True,
                status=OutcomeStatus.COMMITTED,
                cost="0.00137500",
                calls=1,
                stated_rows=1,
            ),
            address,
        ),
        (
            "committed-note",
            _receipt(
                "committed-note",
                17,
                note,
                scope="notes-agent",
                tenants=("initech",),
                admitted=True,
                status=OutcomeStatus.COMMITTED,
                cost="0.00088000",
                calls=1,
                stated_rows=1,
            ),
            note,
        ),
        ("refused-tenant-wipe", wipe_receipt, wipe),
        (
            "scoped-repair",
            _receipt(
                "scoped-repair",
                41,
                repair,
                scope="support-agent",
                tenants=("acme",),
                admitted=True,
                status=OutcomeStatus.COMMITTED,
                cost="0.00221000",
                calls=1,
                stated_rows=1,
                repair_of=wipe_receipt.receipt_id,
            ),
            repair,
        ),
        (
            "recovered-commit",
            _receipt(
                "recovered-commit",
                52,
                recovered,
                scope="fulfilment-agent",
                tenants=("acme",),
                admitted=True,
                status=OutcomeStatus.RECOVERED_COMMITTED,
                cost="0.00104500",
                calls=1,
                stated_rows=1,
                escrow_seq=418,
            ),
            recovered,
        ),
        (
            "halted-scope",
            _receipt(
                "halted-scope",
                58,
                halted,
                scope="support-agent",
                tenants=("umbrella",),
                admitted=True,
                status=OutcomeStatus.REFUSED,
                cost="0.00096000",
                calls=1,
                stated_rows=1,
            ),
            halted,
        ),
    ]


# --------------------------------------------------------------------------
# Vector files
# --------------------------------------------------------------------------


def _canonical_vectors() -> dict[str, Any]:
    cases = [
        ("sorted-keys", {"b": 1, "a": 2, "c": {"z": True, "y": None}}),
        ("utf16-key-order", {"": 1, "\U0001f600": 2, "a": 3, "é": 4}),
        (
            "string-escapes",
            {
                "s": 'quote" backslash\\ newline\n tab\t ctrl\u0001 del\u007f nbsp'
                + chr(0xA0)
                + " ls"
                + chr(0x2028)
                + " "
                + chr(0x1F600)
            },
        ),
        ("integers", {"max": 2**53 - 1, "min": -(2**53 - 1), "zero": 0, "negative": -7}),
        ("nesting", {"a": [], "b": {}, "c": [[], [{}], [1, "x", False, None]]}),
    ]
    rejects = [
        ("float", '{"a":1.5}'),
        ("exponent", '{"a":1e3}'),
        ("duplicate-key", '{"a":1,"a":2}'),
        ("nan", '{"a":NaN}'),
        ("unsafe-integer", '{"a":9007199254740992}'),
    ]
    return {
        "description": "RFC 8785 canonical JSON restricted to the ARC1 value domain. "
        "Each 'accept' input must canonicalize to exactly 'canonical' (UTF-8); each "
        "'reject' text must fail to decode or to canonicalize.",
        "accept": [
            {"name": name, "input": value, "canonical": canonical_bytes(value).decode("utf-8")}
            for name, value in cases
        ],
        "reject": [{"name": name, "text": text} for name, text in rejects],
    }


def _merkle_vectors() -> dict[str, Any]:
    leaves = [
        bytes.fromhex(h)
        for h in (
            "",
            "00",
            "10",
            "2021",
            "3031",
            "40414243",
            "5051525354555657",
            "606162636465666768696a6b6c6d6e6f",
        )
    ]
    tree = MerkleTree(leaf_hash(leaf) for leaf in leaves)
    return {
        "description": "RFC 9162 section 2.1: the eight-leaf tree used by the Certificate "
        "Transparency test suites. Leaves are raw leaf data; hash them with "
        "SHA-256(0x00 || data).",
        "leaves": [leaf.hex() for leaf in leaves],
        "roots": [{"size": n, "root": tree.root(n).hex()} for n in range(len(leaves) + 1)],
        "inclusion": [
            {"index": m, "size": n, "path": [p.hex() for p in tree.inclusion_proof(m, n)]}
            for n in range(1, len(leaves) + 1)
            for m in range(n)
        ],
        "consistency": [
            {"old": m, "new": n, "proof": [p.hex() for p in tree.consistency_proof(m, n)]}
            for n in range(1, len(leaves) + 1)
            for m in range(n + 1)
        ],
    }


def _ed25519_vectors() -> dict[str, Any]:
    rfc8032 = [
        (
            "rfc8032-test-1",
            "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
            "",
            "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bac"
            "c61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
        ),
        (
            "rfc8032-test-2",
            "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
            "72",
            "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e"
            "458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
        ),
        (
            "rfc8032-test-3",
            "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
            "af82",
            "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18ff9b538d16f290"
            "ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a",
        ),
    ]
    order = 2**252 + 27742317777372353535851937790883648493
    _name, public, message, signature = rfc8032[2]
    s = int.from_bytes(bytes.fromhex(signature)[32:], "little") + order
    cases = [
        {"name": n, "public": p, "message": m, "signature": sig, "valid": True}
        for n, p, m, sig in rfc8032
    ]
    cases += [
        {
            "name": "wrong-message",
            "public": public,
            "message": "af83",
            "signature": signature,
            "valid": False,
        },
        {
            "name": "non-canonical-s",
            "public": public,
            "message": message,
            "signature": signature[:64] + s.to_bytes(32, "little").hex(),
            "valid": False,
        },
    ]
    return {
        "description": "Ed25519 (RFC 8032). The first three are the RFC's own section 7.1 "
        "tests. An S at or above the group order must be rejected.",
        "cases": cases,
    }


def generate(out: Path) -> None:
    """Write every vector file under ``out``, replacing what is there."""
    issuer = Ed25519Signer(seed("issuer"))
    witness_key = Ed25519Signer(seed("witness"))
    attacker = Ed25519Signer(seed("attacker"))
    internal = HmacKey(seed("internal hmac"))

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / "README.md").write_text(_README, encoding="utf-8")
    keys = out / "keys"
    keys.mkdir()
    (keys / "issuer.pub").write_text(issuer.public_key().spec() + "\n")
    (keys / "issuer.seed").write_text(seed("issuer").hex() + "\n")
    (keys / "witness.pub").write_text(witness_key.public_key().spec() + "\n")
    (keys / "witness.seed").write_text(seed("witness").hex() + "\n")
    (keys / "internal.hmac").write_text(internal.spec() + "\n")

    _write_json(out / "canonical.json", _canonical_vectors())
    _write_json(out / "merkle.json", _merkle_vectors())
    _write_json(out / "ed25519.json", _ed25519_vectors())

    scenarios = _scenarios()
    with tempfile.TemporaryDirectory() as scratch:
        work = Path(scratch)
        witness = FileWitness(
            work / "cosignatures.jsonl",
            witness_key,
            witness_id=WITNESS_ID,
            logs={LOG_ID: issuer.public_key()},
            clock=_Clock(_BASE + timedelta(hours=1), timedelta(minutes=5)),
        )
        log = ReceiptLog(
            LOG_ID,
            issuer,
            path=work / "receipts.jsonl",
            witnesses=[witness],
            policy=CheckpointPolicy(every_receipts=10**6, every_seconds=10**9),
            clock=_Clock(_BASE + timedelta(minutes=59), timedelta(minutes=1)),
        )
        receipts: dict[str, ActionReceipt] = {}
        commitments: dict[str, RowCommitment] = {}
        first: Checkpoint | None = None
        unwitnessed: Checkpoint | None = None
        for index, (name, draft, commitment) in enumerate(scenarios):
            receipts[name] = log.issue(draft)
            commitments[name] = commitment
            if index == 2:
                first = log.publish()
            if index == 4:
                unwitnessed = log.checkpoint()
        final = log.publish()
        assert first is not None
        consistency = log.consistency_proof(first.tree_size, final.tree_size)
        bundles = {name: log.bundle(i, final) for i, (name, _, _) in enumerate(scenarios)}
        log.close()
        (out / "log").mkdir()
        shutil.copy(work / "receipts.jsonl", out / "log" / "receipts.jsonl")
        shutil.copy(work / "receipts.jsonl.checkpoints", out / "log" / "receipts.jsonl.checkpoints")
        (out / "witness").mkdir()
        shutil.copy(work / "cosignatures.jsonl", out / "witness" / "cosignatures.jsonl")
    assert unwitnessed is not None

    _write_json(
        out / "log" / "consistency.json",
        {
            "description": "The witness checked this RFC 9162 consistency proof before it "
            "cosigned the second checkpoint.",
            "old": first.to_json(),
            "new": final.to_json(),
            "proof": [p.hex() for p in consistency],
        },
    )

    valid = out / "valid"
    for name in (
        "committed-refund",
        "refused-tenant-wipe",
        "scoped-repair",
        "recovered-commit",
        "halted-scope",
    ):
        _write_json(valid / f"{name}.bundle.json", bundles[name].to_json())
    refund, wipe = receipts["committed-refund"], receipts["refused-tenant-wipe"]
    refund_rows = commitments["committed-refund"].disclose([0, 2], receipt_id=refund.receipt_id)
    wipe_rows = commitments["refused-tenant-wipe"].disclose([5, 130], receipt_id=wipe.receipt_id)
    _write_json(valid / "committed-refund.rows.json", refund_rows.to_json())
    _write_json(valid / "refused-tenant-wipe.rows.json", wipe_rows.to_json())
    internal_receipt = replace(
        scenarios[1][1], receipt_id=_uuid("receipt:internal-hmac"), anchors=Anchors()
    ).sign(internal)
    _write_json(valid / "internal-hmac.receipt.json", internal_receipt.to_json())

    invalid = out / "invalid"
    good = bundles["committed-refund"].to_json()

    tampered = json.loads(json.dumps(good))
    tampered["receipt"]["cost"]["settled_usd"] = "0.00049500"
    _write_json(invalid / "field-modified.bundle.json", tampered)

    lowered = replace(refund, cost=replace(refund.cost, settled_usd=Decimal("0.00049500")))
    forged = lowered.sign(attacker)
    assert forged.signature is not None and refund.signature is not None
    forged = replace(
        forged,
        signature=Signature(forged.signature.alg, refund.signature.key_id, forged.signature.value),
    )
    _write_json(
        invalid / "forged-signature.bundle.json",
        replace(bundles["committed-refund"], receipt=forged).to_json(),
    )

    confusion_key = HmacKey(issuer.public_key().raw, key_id=issuer.key_id)
    confused = refund.sign(confusion_key)
    _write_json(
        invalid / "alg-confusion.bundle.json",
        replace(bundles["committed-refund"], receipt=confused).to_json(),
    )

    checkpoint = json.loads(json.dumps(good))
    checkpoint["checkpoint"]["tree_size"] = 6
    checkpoint["inclusion"]["tree_size"] = 6
    _write_json(invalid / "checkpoint-forged.bundle.json", checkpoint)

    ordered = [receipts[name] for name, _, _ in scenarios]
    reordered = [ordered[1], ordered[0], *ordered[2:]]
    tree = MerkleTree(r.leaf_hash() for r in reordered)
    reordered_checkpoint = Checkpoint(
        log_id=LOG_ID,
        tree_size=len(reordered),
        root_hash=tree.root().hex(),
        issued_at=_BASE + timedelta(hours=2),
    ).sign(issuer)
    _write_json(
        invalid / "reordered-log.bundle.json",
        ReceiptBundle(
            receipt=refund,
            inclusion=InclusionProof(
                0, len(reordered), tuple(p.hex() for p in tree.inclusion_proof(0))
            ),
            checkpoint=reordered_checkpoint,
        ).to_json(),
    )
    _write_json(
        invalid / "leaf-moved.bundle.json",
        ReceiptBundle(
            receipt=refund,
            inclusion=InclusionProof(
                1, len(reordered), tuple(p.hex() for p in tree.inclusion_proof(1))
            ),
            checkpoint=reordered_checkpoint,
        ).to_json(),
    )

    _write_json(
        invalid / "unwitnessed.bundle.json",
        ReceiptBundle(
            receipt=refund,
            inclusion=InclusionProof(
                0,
                unwitnessed.tree_size,
                tuple(
                    p.hex()
                    for p in MerkleTree(
                        r.leaf_hash() for r in ordered[: unwitnessed.tree_size]
                    ).inclusion_proof(0)
                ),
            ),
            checkpoint=unwitnessed,
        ).to_json(),
    )

    fork_draft = replace(scenarios[6][1], outcome=Outcome(OutcomeStatus.COMMITTED, "stage:forged"))
    fork_receipt = fork_draft.with_log_anchor(LOG_ID, 6).sign(issuer)
    forked = [*ordered[:6], fork_receipt]
    fork_tree = MerkleTree(r.leaf_hash() for r in forked)
    fork_checkpoint = Checkpoint(
        log_id=LOG_ID,
        tree_size=7,
        root_hash=fork_tree.root().hex(),
        issued_at=_BASE + timedelta(hours=3),
    ).sign(issuer)
    _write_json(
        invalid / "split-view.bundle.json",
        ReceiptBundle(
            receipt=fork_receipt,
            inclusion=InclusionProof(6, 7, tuple(p.hex() for p in fork_tree.inclusion_proof(6))),
            checkpoint=fork_checkpoint,
        ).to_json(),
    )

    modified_rows = refund_rows.to_json()
    modified_rows["rows"][0]["row"]["after"]["status"] = "paid"
    _write_json(invalid / "row-modified.rows.json", modified_rows)
    moved_rows = refund_rows.to_json()
    moved_rows["rows"][1]["index"] = 1
    _write_json(invalid / "row-moved.rows.json", moved_rows)

    text = json.dumps(good, indent=2)
    (invalid / "duplicate-key.bundle.json").write_text(
        text.replace('"v": "ARC1-bundle",', '"v": "ARC1-bundle",\n  "v": "ARC1-bundle",', 1),
        encoding="utf-8",
    )
    (invalid / "float-amount.bundle.json").write_text(
        text.replace('"settled_usd": "0.00549500"', '"settled_usd": 0.005495', 1), encoding="utf-8"
    )
    unknown = json.loads(json.dumps(good))
    unknown["receipt"]["effect"]["confidence"] = "high"
    _write_json(invalid / "unknown-field.bundle.json", unknown)

    _write_json(out / "manifest.json", _manifest())


def _manifest() -> dict[str, Any]:
    issuer = ["--pubkey", "keys/issuer.pub"]
    witnessed = [
        *issuer,
        "--witness",
        "witness/cosignatures.jsonl",
        "--witness-pubkey",
        "keys/witness.pub",
    ]

    def case(name: str, exit_code: int, args: list[str], what: str) -> dict[str, Any]:
        return {"name": name, "exit": exit_code, "args": args, "description": what}

    return {
        "description": "Run `agentgov verify-receipt` with 'args' (paths relative to this "
        "directory) and expect 'exit'. 0 pass, 3 malformed, 4 receipt signature, 5 log "
        "inclusion, 6 witness, 8 rows.",
        "cases": [
            case(
                "committed-refund",
                0,
                [
                    "valid/committed-refund.bundle.json",
                    *witnessed,
                    "--rows",
                    "valid/committed-refund.rows.json",
                ],
                "a committed refund, witnessed, with two of its three rows disclosed",
            ),
            case(
                "refused-tenant-wipe",
                0,
                [
                    "valid/refused-tenant-wipe.bundle.json",
                    *witnessed,
                    "--rows",
                    "valid/refused-tenant-wipe.rows.json",
                ],
                "a refused 229-row cross-tenant plan: refusals get receipts too",
            ),
            case(
                "scoped-repair",
                0,
                ["valid/scoped-repair.bundle.json", *witnessed],
                "a scoped plan that repairs the refused one (decision.repair_of)",
            ),
            case(
                "recovered-commit",
                0,
                ["valid/recovered-commit.bundle.json", *witnessed],
                "a commit resolved after a crash from its commit marker",
            ),
            case(
                "halted-scope",
                0,
                ["valid/halted-scope.bundle.json", *witnessed],
                "admitted by every check, refused because the scope was halted",
            ),
            case(
                "internal-hmac",
                0,
                ["valid/internal-hmac.receipt.json", "--pubkey", "keys/internal.hmac"],
                "a bare receipt signed with an internal HMAC key",
            ),
            case(
                "field-modified",
                4,
                ["invalid/field-modified.bundle.json", *issuer],
                "settled_usd lowered after signing",
            ),
            case(
                "forged-signature",
                4,
                ["invalid/forged-signature.bundle.json", *issuer],
                "re-signed by another key that claims the issuer's key_id",
            ),
            case(
                "alg-confusion",
                4,
                ["invalid/alg-confusion.bundle.json", *issuer],
                "an HMAC keyed with the issuer's public key, claiming hmac-sha256",
            ),
            case(
                "checkpoint-forged",
                5,
                ["invalid/checkpoint-forged.bundle.json", *issuer],
                "the checkpoint's tree size edited after signing",
            ),
            case(
                "reordered-log",
                5,
                ["invalid/reordered-log.bundle.json", *issuer],
                "the log operator swapped two leaves and signed the new root",
            ),
            case(
                "leaf-moved",
                5,
                ["invalid/leaf-moved.bundle.json", *issuer],
                "the same swap, with a valid audit path to the receipt's new index: only the "
                "position signed into the receipt catches it",
            ),
            case(
                "unwitnessed",
                6,
                ["invalid/unwitnessed.bundle.json", *witnessed],
                "a real checkpoint the witness never saw",
            ),
            case(
                "split-view",
                6,
                ["invalid/split-view.bundle.json", *witnessed],
                "a forked log: a different receipt 6 under a signed root no witness cosigned",
            ),
            case(
                "row-modified",
                8,
                [
                    "valid/committed-refund.bundle.json",
                    *issuer,
                    "--rows",
                    "invalid/row-modified.rows.json",
                ],
                "a disclosed row edited after commitment",
            ),
            case(
                "row-moved",
                8,
                [
                    "valid/committed-refund.bundle.json",
                    *issuer,
                    "--rows",
                    "invalid/row-moved.rows.json",
                ],
                "a disclosed row presented at another index",
            ),
            case(
                "rows-of-another-receipt",
                8,
                [
                    "valid/committed-refund.bundle.json",
                    *issuer,
                    "--rows",
                    "valid/refused-tenant-wipe.rows.json",
                ],
                "a valid disclosure, of a different receipt",
            ),
            case(
                "duplicate-key",
                3,
                ["invalid/duplicate-key.bundle.json", *issuer],
                "a duplicate object key",
            ),
            case(
                "float-amount",
                3,
                ["invalid/float-amount.bundle.json", *issuer],
                "a float where a decimal string belongs",
            ),
            case(
                "unknown-field",
                3,
                ["invalid/unknown-field.bundle.json", *issuer],
                "a field the schema does not define",
            ),
        ],
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--out", default=str(Path(__file__).resolve().parent.parent / "vectors" / "arc1")
    )
    args = parser.parse_args(argv)
    generate(Path(args.out))
    print(f"wrote ARC1 vectors to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
